### ISSUE TITLE
Improve system availability

### ISSUE THREAD

**Issue by danse** [eHealthAfrica/sense-dispatch#12]
Pouch proved to be not fully reliable in following live changes, since it will report a connection timeout as an error, which might lead to loss of change events. See https://github.com/eHealthAfrica/sense-dashboard/issues/144 and https://github.com/eHealthAfrica/ehealth-deployment/issues/635. A better alternative would be to use [Follow](https://github.com/iriscouch/follow) or Nano, which embeds Follow

**Comment by danse** [comment]
I tried to use Nano but i failed, i will go on with Pouch + Follow:

```
> var db = Nano('http://developers:password@dev-sl-ebola-cases.eocng.org/sense');
undefined
> db.follow()
TypeError: Cannot set property 'db' of undefined
    at followDb (/Users/francesco/repos/sense-dispatch/node_modules/nano/lib/nano.js:320:11)
    at Object.docScope.follow (/Users/francesco/repos/sense-dispatch/node_modules/nano/lib/nano.js:680:16)
    at repl:1:5
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface.<anonymous> (readline.js:323:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:322:11)
```

**Comment by danse** [comment]
alright that was due to wrong test conditions ... i fixed the tests with a slightly ugly mock and stuck with Nano

**Comment by danse** [comment]
Still having problems with changes not detected, switched to Nano + Follow in order to simplify troubleshooting

**Comment by danse** [comment]
It took a lot of time for me to try to debug why Follow was not triggering `change` events, while Pouch does it already. Seems to me that Follow in its current state is not very actively maintained, so i would prefer not to have to rely on it now. I added some logic on top of Pouch, in order to store the last sequence number on start and upon every received change. This guarantees us that no change event will be lost, not even in that split second while the feed is being restarted after a timeout

**Comment by danse** [comment]
I renamed the issue. Before this issue, the system was unavailable for very short amounts of time. Now the system will catch all events

**Comment by danse** [comment]
My attempts to try to switch to Follow are currently available in the branch https://github.com/danse/sense-dispatch/tree/12
